AWSTemplateFormatVersion: '2010-09-09'
Description: "lime"
Parameters:
  instancetype:
    Type: String
Resources:
  limesecgrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: limesecgrp
      SecurityGroupIngress:
      - CidrIp: 22.22.22.22/32
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
  Server:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: craigJ
      ImageId: ami-bf4193c7
      InstanceType: !Ref instancetype
      KeyName:  oregonkeypair
      SecurityGroupIds:
        - !Ref limesecgrp
      IamInstanceProfile: RoleForTestingRoles
      BlockDeviceMappings:
        - DeviceName "/dev/xvda"
          Ebs:
            VolumeSize: 8
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -ex\n"
              - "touch /tmp/hello1\n"
              - "yum install git -y\n"
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user; git clone https://github.com/craigwongva/lime.git > /tmp/u01 2>&1 '\n",
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user/lime; ./userdata-jenkins         > /tmp/u02 2>&1'\n",
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user/lime; ./userdata-j2              > /tmp/u03 2>&1'\n",
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user/lime; ./userdata-nexus-only      > /tmp/u04 2>&1'\n",
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user/lime; ./userdata-grails-green    > /tmp/u05 2>&1'\n",
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user/lime; ./userdata-sonar           > /tmp/u06 2>&1'\n",
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user/lime; ./userdata-phantom         > /tmp/u07 2>&1'\n"
Outputs:
  InstanceID:
    Description: "The Instance ID"
    Value: !GetAtt Server.PublicIp